<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Http\Router;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Spiral\Core\ContainerInterface;
use Spiral\Http\ClientException;
use Spiral\Http\Responses\RedirectResponse;

class Router implements RouterInterface
{
    /**
     * Internal name for primary (default) route. Primary route used to resolve url and perform controller
     * based routing in cases where no other route found.
     *
     * Primary route should support <controller> and <action> parameters. Basically this is multi
     * controller route. Primary route should be instance of spiral DirectRoute or compatible.
     */
    const DEFAULT_ROUTE = 'default';

    /**
     * Container.
     *
     * @invisible
     * @var ContainerInterface
     */
    protected $container = null;

    /**
     * Registered routes.
     *
     * @var RouteInterface[]
     */
    protected $routes = [];

    /**
     * Base path fetched automatically from request attribute "activePath" which is populated by
     * HttpDispatcher while selecting appropriate endpoint. Base path used to correctly resolve route
     * url and pattern when website or module associated with non empty URI path.
     *
     * @var string
     */
    protected $activePath = '/';

    /**
     * Active route instance, this value will be populated only after router successfully handled
     * incoming request.
     *
     * @var RouteInterface|null
     */
    protected $activeRoute = null;

    /**
     * Router middleware used by HttpDispatcher and modules to perform URI based routing with defined
     * endpoint such as controller action, closure or middleware.
     *
     * @param ContainerInterface   $container
     * @param RouteInterface[]     $routes  Pre-defined array of routes (if were collected externally).
     * @param RouteInterface|array $default Default route or options to construct instance of DirectRoute.
     */
    public function __construct(ContainerInterface $container, array $routes = [], array $default = [])
    {
        $this->container = $container;

        foreach ($routes as $route)
        {
            if (!$route instanceof RouteInterface)
            {
                throw new \InvalidArgumentException("Routes should be array of Route instances.");
            }

            //Name aliasing is required to perform URL generation later.
            $this->routes[$route->getName()] = $route;
        }

        if ($default instanceof RouteInterface)
        {
            $this->routes[self::DEFAULT_ROUTE] = $default;

            return;
        }

        if (!isset($this->routes[self::DEFAULT_ROUTE]) && !empty($default))
        {
            //Registering default route which should handle all unhandled controllers
            $this->routes[self::DEFAULT_ROUTE] = new DirectRoute(
                self::DEFAULT_ROUTE,
                $default['pattern'],
                $default['namespace'],
                $default['postfix'],
                $default['defaults'],
                $default['controllers']
            );
        }
    }

    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param ServerRequestInterface $request Server request instance.
     * @param \Closure               $next    Next middleware/target.
     * @param object|null            $context Pipeline context, can be HttpDispatcher, Route or module.
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, \Closure $next = null, $context = null)
    {
        //Open router scope
        $outerRouter = $this->container->replace(self::class, $this);

        $this->activePath = $request->getAttribute('activePath', $this->activePath);
        if (!$this->activeRoute = $this->findRoute($request, $this->activePath))
        {
            throw new ClientException(ClientException::NOT_FOUND);
        }

        //Executing found route
        $response = $this->activeRoute->perform(
            $request->withAttribute('route', $this->activeRoute),
            $this->container
        );

        //Close router scope
        $this->container->restore($outerRouter);

        return $response;
    }

    /**
     * Find route matched for given request.
     *
     * @param ServerRequestInterface $request
     * @param string                 $basePath
     * @return null|RouteInterface
     */
    protected function findRoute(ServerRequestInterface $request, $basePath)
    {
        foreach ($this->routes as $route)
        {
            if ($route->match($request, $basePath))
            {
                return $route;
            }
        }

        return null;
    }

    /**
     * Add new Route instance to router stack, route has to be added before router handled request.
     *
     * @param RouteInterface $route
     */
    public function addRoute(RouteInterface $route)
    {
        $this->routes[] = $route;
    }

    /**
     * All registered routes.
     *
     * @return RouteInterface[]
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * Get route by name. Use Router::DEFAULT to get default route.
     *
     * @param string $route
     * @return RouteInterface
     * @throws RouterException
     */
    public function getRoute($route)
    {
        if (!isset($this->routes[$route]))
        {
            throw new RouterException("Undefined route '{$route}'.");
        }

        return $this->routes[$route];
    }

    /**
     * Get currently active route, this value will be populated only after router successfully handled
     * incoming request.
     *
     * @return RouteInterface|null
     */
    public function activeRoute()
    {
        return $this->activeRoute;
    }

    /**
     * Generate url using route name and set of provided parameters. Parameters will be automatically
     * injected to route pattern and prefixed with activePath value.
     *
     * You can enter controller::action type route, in this case appropriate controller and action
     * will be injected into default route as controller and action parameters accordingly. Default
     * route should be instance of spiral DirectRoute or compatible.
     *
     * Example:
     * $this->router->url('post::view', ['id' => 1]);
     * $this->router->url('post/view', ['id' => 1]);
     *
     * @param string $route      Route name.
     * @param array  $parameters Route parameters including controller name, action and etc.
     * @return string
     * @throws RouterException
     */
    public function url($route, array $parameters = [])
    {
        if (!isset($this->routes[$route]))
        {
            //Will be handled via default route where route name is specified as controller::action
            if (
                strpos($route, RouteInterface::CONTROLLER_SEPARATOR) == false
                && strpos($route, '/') === false
            )
            {
                throw new RouterException(
                    "Unable to locate route or use default route with controller/action pattern."
                );
            }

            //We can fetch controller and action names from url
            list($controller, $action) = explode(
                RouteInterface::CONTROLLER_SEPARATOR,
                str_replace('/', RouteInterface::CONTROLLER_SEPARATOR, $route)
            );

            $parameters = compact('controller', 'action') + $parameters;
            $route = self::DEFAULT_ROUTE;
        }

        return $this->routes[$route]->createURL($parameters, $this->activePath);
    }

    /**
     * Generate redirect based on url rendered using specified route pattern.
     *
     * You can enter controller::action type route, in this case appropriate controller and action
     * will be injected into default route as controller and action parameters accordingly. Default
     * route should be instance of spiral DirectRoute or compatible.
     *
     * Example:
     * return $this->router->redirect('post::view', ['id' => 1]);
     *
     * @param string $route      Route name.
     * @param array  $parameters Route parameters including controller name, action and etc.
     * @return RedirectResponse
     */
    public function redirect($route, array $parameters = [])
    {
        return new RedirectResponse($this->url($route, $parameters));
    }
}