<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Http\Middlewares;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Spiral\Http\HttpDispatcher;
use Spiral\Http\MiddlewareInterface;

class ApplicationHeaders implements MiddlewareInterface
{
    /**
     * Global headers list.
     *
     * @var array
     */
    protected $headers = [];

    /**
     * ApplicationHeaders middleware will make sure that all requested global headers sent.
     *
     * @param HttpDispatcher $http
     */
    public function __construct(HttpDispatcher $http)
    {
        $this->headers = $http->getConfig()['headers'];
    }

    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param ServerRequestInterface $request Server request instance.
     * @param \Closure               $next    Next middleware/target.
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, \Closure $next = null)
    {
        /**
         * @var ResponseInterface $response
         */
        $response = $next($request);

        foreach ($this->headers as $header => $value)
        {
            if (!$response->hasHeader($header))
            {
                $response = $response->withHeader($header, $value);
            }
        }

        return $response;
    }
}